default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hr_department_development

test:
  <<: *default
  database: hr_department_test

production:
  <<: *default
  database: hr_department_production
  username: hr_department
  password: <%= ENV['HR_DEPARTMENT_DATABASE_PASSWORD'] %>
